In [73]:
import torch
import pandas
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1


In [74]:
scalar = torch.tensor(7)
scalar.shape

torch.Size([])

In [75]:
vector = torch.tensor([1, 2, 3, 4, 5])
vector.shape

torch.Size([5])

In [76]:
MATRIX = torch.tensor([[1, 2, 3], [4, 5, 6]])
MATRIX.shape

torch.Size([2, 3])

In [77]:
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
TENSOR.shape
TENSOR.ndim

3

In [78]:
rand_tensor = torch.rand(2,2,3)
rand_tensor

tensor([[[0.6456, 0.4599, 0.7707],
         [0.5813, 0.7975, 0.2277]],

        [[0.1809, 0.2628, 0.4264],
         [0.4133, 0.4448, 0.5633]]])

In [79]:
rand_img = torch.rand(28, 28, 3)
rand_img.shape, rand_img.ndim

(torch.Size([28, 28, 3]), 3)

In [80]:
zeroes = torch.zeros(size=(3, 3))
ones = torch.ones(size=(3, 3))
zeroes, ones

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]))

In [81]:
torch.zeros_like(ones)
torch.rand_like(ones)
torch.full_like(ones, fill_value=42)


tensor([[42., 42., 42.],
        [42., 42., 42.],
        [42., 42., 42.]])

In [82]:
testor = torch.tensor([1, 2, 3], dtype=torch.float16, device='cpu', requires_grad=True)
testor = testor.type(torch.float32)
testor.dtype

torch.float32

In [83]:
tensor = torch.rand(4, 3)
tensor

tensor([[0.2948, 0.9134, 0.8885],
        [0.7578, 0.4028, 0.2222],
        [0.2162, 0.3011, 0.8085],
        [0.4720, 0.4150, 0.0455]])

In [84]:
tensor * 10


tensor([[2.9481, 9.1341, 8.8849],
        [7.5777, 4.0282, 2.2219],
        [2.1624, 3.0107, 8.0852],
        [4.7201, 4.1496, 0.4550]])

In [85]:
tensor @ tensor.t()

tensor([[1.7106, 0.7887, 1.0571, 0.5586],
        [0.7887, 0.7858, 0.4648, 0.5349],
        [1.0571, 0.4648, 0.7911, 0.2638],
        [0.5586, 0.5349, 0.2638, 0.3970]])

In [86]:
tensor = torch.arange(4)
tensor

tensor([0, 1, 2, 3])

In [87]:
tensor = tensor.type(torch.float32)
torch.min(tensor), torch.max(tensor), torch.sum(tensor), torch.mean(tensor)

(tensor(0.), tensor(3.), tensor(6.), tensor(1.5000))

In [88]:
torch.argmax(tensor), torch.argmin(tensor)

(tensor(3), tensor(0))

In [89]:
#find index of mean value if it exists
tensor = torch.full_like(tensor, fill_value=3)
torch.eq(tensor, torch.mean(tensor)), tensor.dtype


(tensor([True, True, True, True]), torch.float32)

In [90]:
tensor = torch.arange(1., 10.)
tensor.reshape(3, 3)


tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [91]:
t_view = tensor.view(3, 3)
t_view[0][0] = 20.
t_view, tensor

(tensor([[20.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]]),
 tensor([20.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]))

In [93]:
stack = torch.stack([tensor])
stack.shape


torch.Size([1, 9])

In [101]:
squeezed = torch.squeeze(stack)
unsqueezed = torch.unsqueeze(tensor, dim=0)
unsqueezed_vert = torch.unsqueeze(tensor, dim=1)
squeezed, unsqueezed, unsqueezed_vert, squeezed.shape, unsqueezed.shape, unsqueezed_vert.shape


(tensor([20.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]),
 tensor([[20.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]),
 tensor([[20.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.]]),
 torch.Size([9]),
 torch.Size([1, 9]),
 torch.Size([9, 1]))

In [105]:
x_img = torch.rand(1920, 1080, 3)
x_perm = x_img.permute(2, 0, 1)

x_img.shape, x_perm.shape

(torch.Size([1920, 1080, 3]), torch.Size([3, 1920, 1080]))

In [108]:
x_img[0][0][0] = 2000
x_perm[0][0][0]

tensor(2000.)

In [111]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [115]:
x[0, 2, 2], x[0, :, 2]

(tensor(9), tensor([3, 6, 9]))

In [121]:
import numpy as np

arr = np.arange(1.0, 8.0)
tensor = torch.from_numpy(arr).type(torch.float32)
arr, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [125]:
tensor = torch.ones(7)
np_tensor = tensor.numpy().astype(np.float64)
tensor, np_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1., 1., 1.]))

In [127]:
rand_A = torch.rand(3, 3)
rand_B = torch.rand(3, 3)

rand_A == rand_B

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [130]:
seed = 42

torch.manual_seed(seed)
rand_A = torch.rand(3, 3)

torch.manual_seed(seed)
rand_B = torch.rand(3, 3)

rand_A == rand_B

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [131]:
#make code device agnostic
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'